export const channels = {
  appSettings: 'app:settings',
  appSetTwelveDataKey: 'app:set-twelve-data-key',
  authRegister: 'auth:register',
  authLogin: 'auth:login',
  authLogout: 'auth:logout',
  authSession: 'auth:session',
  authDeleteAccount: 'auth:delete-account',
  gamesList: 'games:list',
  gamesCreate: 'games:create',
  gamesLoad: 'games:load',
  gamesSyncClock: 'games:sync-clock',
  gamesSetTimeMultiplier: 'games:set-time-multiplier',
  gamesRemove: 'games:remove',
  savesList: 'saves:list',
  savesCreate: 'saves:create',
  savesRestore: 'saves:restore',
  savesRemove: 'saves:remove',
  marketSearch: 'market:search',
  marketQuote: 'market:quote',
  marketCandles: 'market:candles',
  tradingExecute: 'trading:execute',
  tradingPortfolio: 'trading:portfolio',
  adminMutate: 'admin:mutate',
} as const;
